apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quoteservice-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quoteservice-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: quoteservice
    namespace: default
roleRef:
  kind: Role
  name: quoteservice-role
  apiGroup: rbac.authorization.k8s.io

